# Create Namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: catalin
  labels:
    name: catalin
---

# Git Repo & Secret
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: state-repo
  namespace: catalin
spec:
  interval: 5m0s
  url: https://github.com/CatalinStratulat/FluxTests
  ref:
    branch: main
  secretRef:
    name: flux-secret

---
apiVersion: v1
data:
  password: Z2hwX0lBaVlmZVlLdW9jWmRsVkYwbnpkOG4xM3E5RlMzajM1U3lYUw==
  username: Q2F0YWxpblN0cmF0dWxhdA==
kind: Secret
metadata:
  namespace: catalin
  name: flux-secret
type: Opaque

---
# Helm Repo & Secret

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: customerstagingregistry
  namespace: catalin
spec:
  type: "oci"
  interval: 1m0s
  secretRef:
    name: customerstagingreg
  url: oci://customerstagingregistry.azurecr.io/helm
---
apiVersion: v1
kind: Secret
data:
  password: cWhIUUhmNWFCUkNUdHdNMWVTVjRaSkYvUW1VVTMyUlE=
  username: Y3VzdG9tZXJzdGFnaW5ncmVnaXN0cnk=
metadata:
  creationTimestamp: "2023-03-15T16:34:22Z"
  name: customerstagingreg
  namespace: catalin
  resourceVersion: "31442"
  uid: 3544ef13-a146-4945-8f87-feffc219bc1c
type: Opaque

---
# Kustomization

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-kz
  namespace: catalin
spec:
  force: true
  interval: 1m0s
  path: ./infra
  prune: true
  sourceRef:
    kind: GitRepository
    name: state-repo
  targetNamespace: default
